"""Typed request-scenario bundle shared by the R5 source and tools layers.

Keeping this contract in ``r4r`` prevents the strict scenario builder from
using a class-name/attribute duck type merely because the original diagnostic
builder lived under ``tools``.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from r4r.errors import ValidationError
from r4r.models.base import ContractModel
from r4r.request_contracts import AdmittedRequestVector, RawRequestVector, StrategicReportResult
from r4r.request_generation import RequestConstruction
from r4r.serialization import canonical_hash
from r4r.types import IdentifierVector, Sha256


@dataclass(frozen=True, slots=True)
class DiagnosticRequestScenarioBundle(ContractModel):
    """All request layers for one diagnostic reference/reported scenario."""

    participant_ids: IdentifierVector
    participant_registry_hash: Sha256
    request_construction: RequestConstruction
    reference_raw_request: RawRequestVector
    reference_admitted_request: AdmittedRequestVector
    reported_raw_request: RawRequestVector
    reported_admitted_request: AdmittedRequestVector
    strategic_report: StrategicReportResult
    status: str = "DIAGNOSTIC_ONLY"
    serialization_id = "diagnostic_request_scenario_bundle.v1"

    def __post_init__(self) -> None:
        if not isinstance(self.participant_ids, IdentifierVector) or not self.participant_ids.values:
            raise ValidationError("participant_ids must be a non-empty IdentifierVector")
        if not isinstance(self.participant_registry_hash, Sha256):
            raise ValidationError("participant_registry_hash must be Sha256")
        if not isinstance(self.request_construction, RequestConstruction):
            raise ValidationError("request_construction must be RequestConstruction")
        expected_types = {
            "reference_raw_request": RawRequestVector,
            "reference_admitted_request": AdmittedRequestVector,
            "reported_raw_request": RawRequestVector,
            "reported_admitted_request": AdmittedRequestVector,
            "strategic_report": StrategicReportResult,
        }
        for name, expected_type in expected_types.items():
            if not isinstance(getattr(self, name), expected_type):
                raise ValidationError(f"{name} has an invalid request-layer type")
        for name in (
            "reference_raw_request",
            "reference_admitted_request",
            "reported_raw_request",
            "reported_admitted_request",
        ):
            if getattr(self, name).participant_ids != self.participant_ids:
                raise ValidationError(f"{name} participant order does not match bundle")
        for name in ("reference_raw_request", "reported_raw_request"):
            if getattr(self, name).participant_registry_hash != self.participant_registry_hash:
                raise ValidationError(f"{name} participant registry hash does not match bundle")
        if self.reference_raw_request.values_mw != self.request_construction.actual_request_mw:
            raise ValidationError("reference raw request is not generated by RequestConstruction")
        if self.strategic_report.reference_raw_request != self.reference_raw_request:
            raise ValidationError("strategic report reference layer does not match bundle")
        if self.reference_admitted_request.source_side.value != "reference":
            raise ValidationError("reference admitted request has wrong side")
        if self.reference_admitted_request.raw_request_hash != self.reference_raw_request.request_hash:
            raise ValidationError("reference admitted request must bind reference raw request")
        if self.reference_admitted_request.raw_values_mw != self.reference_raw_request.values_mw:
            raise ValidationError("reference admission must retain reference raw values")
        if self.strategic_report.reported_raw_request != self.reported_raw_request:
            raise ValidationError("strategic report raw layer does not match bundle")
        if self.strategic_report.reported_admitted_request != self.reported_admitted_request:
            raise ValidationError("strategic report admitted layer does not match bundle")
        if self.reported_admitted_request.raw_request_hash != self.reported_raw_request.request_hash:
            raise ValidationError("reported admitted request must bind reported raw request")
        if self.reported_admitted_request.raw_values_mw != self.reported_raw_request.values_mw:
            raise ValidationError("reported admission must retain reported raw values")
        if self.status != "DIAGNOSTIC_ONLY":
            raise ValidationError("request scenario bundles cannot be promoted by this interface")

    def to_json(self) -> dict[str, Any]:
        return {
            "participant_ids": self.participant_ids.to_json(),
            "participant_registry_hash": self.participant_registry_hash.to_json(),
            "request_construction": self.request_construction.to_json(),
            "reference_raw_request": self.reference_raw_request.to_json(),
            "reference_admitted_request": self.reference_admitted_request.to_json(),
            "reported_raw_request": self.reported_raw_request.to_json(),
            "reported_admitted_request": self.reported_admitted_request.to_json(),
            "strategic_report": self.strategic_report.to_json(),
            "status": self.status,
        }

    @property
    def bundle_hash(self) -> Sha256:
        return Sha256(canonical_hash({"serialization_id": self.serialization_id, "fields": self.to_json()}))


__all__ = ["DiagnosticRequestScenarioBundle"]
